// F2pPlatform/web/libs/shared/ui/src/lib/f2p-home-tiles.component.ts
import { Component, input, output } from '@angular/core';
import { NgClass } from '@angular/common';
import { HomeTile } from './home-tile.model';

@Component({
  selector: 'f2p-home-tiles',
  imports: [NgClass],
  templateUrl: './f2p-home-tiles.component.html',
})
export class F2pHomeTilesComponent {
  readonly tiles = input.required<HomeTile[]>();
  readonly tileSelect = output<HomeTile>();

  accentClass(tile: HomeTile): Record<string, boolean> {
    return {
      'border-t-4 border-t-f2p-brand': tile.accent === 'brand',
      'border-t-4 border-t-f2p-success': tile.accent === 'success',
      'border-t-4 border-t-f2p-warning': tile.accent === 'warning',
    };
  }

  onTileClick(tile: HomeTile): void {
    this.tileSelect.emit(tile);
  }
}

<div class="f2p-tile-grid">
  @for (tile of tiles(); track tile.route) {
    <article
      class="f2ps-tile f2ps-clickable flex flex-col justify-end p-4"
      [ngClass]="accentClass(tile)"
      [attr.data-testid]="'home-tile-' + tile.label.toLowerCase()"
      (click)="onTileClick(tile)"
      (keyup.enter)="onTileClick(tile)"
      tabindex="0"
      role="button"
    >
      <p class="f2ps-tile__label">{{ tile.label }}</p>
      <p class="f2ps-tile__meta">{{ tile.meta }}</p>
    </article>
  }
</div>

// FloorganiseCss/showcase/src/components/F2pHomeTiles.vue
<script setup lang="ts">
export type HomeTile = {
  label: string
  meta: string
  accent?: 'brand' | 'success' | 'warning'
}

defineProps<{
  tiles: HomeTile[]
}>()
</script>

<template>
  <!-- Semantic aliases only: f2ps-tile + f2p-tile-grid -->
  <div class="f2p-tile-grid">
    <article
      v-for="tile in tiles"
      :key="tile.label"
      class="f2ps-tile f2ps-clickable flex flex-col justify-end p-4"
      :class="{
        'border-t-4 border-t-f2p-brand': tile.accent === 'brand',
        'border-t-4 border-t-f2p-success': tile.accent === 'success',
        'border-t-4 border-t-f2p-warning': tile.accent === 'warning',
      }"
    >
      <p class="f2ps-tile__label">{{ tile.label }}</p>
      <p class="f2ps-tile__meta">{{ tile.meta }}</p>
    </article>
  </div>
</template>
